// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotorAsinBasketRobot.DataAccess.Concrete.EntityFramework.Context;

#nullable disable

namespace MotorAsinBasketRobot.DataAccess.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    partial class AdminDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MotorAsinBasketRobot.Entities.Concrete.MASqlConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationIntent")
                        .HasMaxLength(250)
                        .HasColumnType("NVarChar");

                    b.Property<string>("Certificate")
                        .HasMaxLength(250)
                        .HasColumnType("NVarChar");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatorId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(250)
                        .HasColumnType("NVarChar");

                    b.Property<string>("DbName")
                        .HasMaxLength(250)
                        .HasColumnType("NVarChar");

                    b.Property<long?>("DeletedId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Encrypt")
                        .HasMaxLength(250)
                        .HasColumnType("NVarChar");

                    b.Property<byte?>("EnmConnetion")
                        .HasColumnType("TinyInt");

                    b.Property<string>("Failover")
                        .HasMaxLength(250)
                        .HasColumnType("NVarChar");

                    b.Property<byte>("Format")
                        .HasMaxLength(250)
                        .HasColumnType("TinyInt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifiedId")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .HasMaxLength(250)
                        .HasColumnType("NVarChar");

                    b.Property<string>("ServerName")
                        .HasMaxLength(250)
                        .HasColumnType("NVarChar");

                    b.Property<double?>("Timeout")
                        .HasMaxLength(250)
                        .HasColumnType("Float");

                    b.Property<string>("UserName")
                        .HasMaxLength(250)
                        .HasColumnType("NVarChar");

                    b.HasKey("Id");

                    b.ToTable("MASqlConnection", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
